#!/usr/bin/Rscript --no-restore --no-save 


args <- commandArgs(trailingOnly = TRUE)

library(XML)
library(RCurl)

destdir <- "/Your/File/Path/Here"

getimgurURL<- function(url, appended = "", destdir) {
  # Parse out images waiting to be shown in preview gallery 
  # These exist regardless of the size of the album
  thumbs <- getNodeSet(xmlRoot(htmlTreeParse(url)), "//body//img[@class='unloaded thumb-title']")
  # Grab image urls
  thumbs.uri <- mapply(function(x) thumbs[[x]]$attributes[['data-src']], 1:length(thumbs))
  # Thumbnails on imgur are denoted with a trailing "s" in the filename
  url.final <- sub("s.", ".", thumbs.uri, fixed = TRUE)
  # Album title becomes folder title
  dirtitle <- file.path(destdir, unlist(getNodeSet(xmlRoot(htmlTreeParse(url)), "//head//title"))[[3]])
  if (grepl("Photo Album", dirtitle)) dirtitle <- paste(dirtitle, appended, sep = "_")
  if (file.exists(dirtitle)) return(NULL)
  filetitles <- file.path(dirtitle, basename(url.final))
  dir.create(dirtitle)
  file.create(filetitles)
  #I could vectorize this but the local processor isn't the bottleneck here
  for (i in seq_along(thumbs)) {
  	writeBin(getBinaryURL(url.final[i]), filetitles[i])
  }
}

for (i in 1:length(args)) getimgurURL(url = args[i], appended = i, destdir = destdir)

q()